# References:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8

before_install:
- gem install cocoapods -v 1.1.0.rc.2 --no-ri --no-rdoc

script:
- set -o pipefail && xcodebuild test -workspace Example/HideKeyboard.xcworkspace -scheme HideKeyboard-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
