# References:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10

before_install:
    - env
    - locale
    - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
- set -o pipefail && xcodebuild -workspace Example/HideKeyboard.xcworkspace -scheme HideKeyboard-Example -sdk iphonesimulator12.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
