# References:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3

before_install:
- gem install cocoapods

script:
- set -o pipefail && xcodebuild test -workspace Example/HideKeyboard.xcworkspace -scheme HideKeyboard-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint